baseURL = "https://fabwu.ch"
languageCode = "en-us"
title = "Fabian Wüthrich"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true


[params]
    author = "Fabian Wüthrich"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Seeking a position in renewable energy to apply my expertise in software development and engineering.
    """
    publicationYear = "2024"

[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "github"
    pre = "<i class='fa fa-github fa-lg'></i>"
    url = "https://github.com/fabwu"
    weight = 30

[[menu.main]]
    identifier = "linkedin"
    pre = "<i class='fa fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/fabian-w%C3%BCthrich/"
    weight = 30

[[menu.main]]
    identifier = "email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:me@fabwu.ch"
    weight = 40
