baseURL = "https://fabwu.ch"
languageCode = "en-us"
title = "Fabian Wüthrich"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true


[params]
    author = "Fabian Wüthrich"
    avatar = "avatar.jpg"
    favicon = "favicon.ico"
    description = """
        Traveling in Central America
    """
    publicationYear = "2024"

[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/fabwu"
    weight = 30

[[menu.main]]
    identifier = "email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:me@fabwu.ch"
    weight = 40
